export const MEETING_ACTIVITIES = [
  "Team meeting",
  "Cross-functional project sync",
  "1:1 with your manager",
  "Sprint planning",
  "Quarterly business review",
  "Weekly check-in",
  "Department all-hands meeting",
  "1:1s with your direct reports",
  "Hiring committee",
  "Bug triage",
  "Design review",
  "Project status review",
  "Quarterly planning",
  "Project retrospective",
  "Brainstorming session",
  "1:1 with your skip-level manager",
  "Standup",
  "Budget planning meeting",
  "Launch review",
  "Candidate interview",
  "Executive reporting",
  "Incident postmortem",
  "Strategy discussion",
  "Performance review",
  "Onboarding session",
  "Metrics review",
  "Vendor evaluation",
  "Project kickoff",
  "Campaign planning",
  "Compliance training",
];

export const NON_MEETING_ACTIVITIES = [
  "Deep focus work",
  "Collaborate with colleagues on a project",
  "Prepare for a meeting to make it effective for all attendees",
  "Analyze customer data for new insights",
  "Review the performance of the latest launch",
  "Learn a new skill through a course",
  "Draft a proposal for a new project",
  "Perfect an executive presentation",
  "Research industry trends",
  "Review and respond to messages",
  "Prioritize and plan upcoming work",
  "Update project documentation",
  "Margins between meetings",
  "Prepare for a performance review",
  "Attend a team-building activity",
  "Brainstorm ideas for a new campaign",
  "Test new software or tools",
  "Attend a professional development workshop",
  "Hallway conversations",
  "Review and edit a colleague's work",
  "Prepare for a client presentation",
  "Provide feedback on a coworker's performance",
  "Develop a new strategy",
  "Mentor a colleague",
  "Conduct user research",
  "Create training materials",
];
