CREATE TYPE "public"."attendance" AS enum (
    'accepted',
    'declined',
    'tentative'
);

CREATE TYPE "public"."provider" AS enum (
    'google',
    'azure'
);

CREATE TABLE "public"."attendee" (
    "event_id" bigint NOT NULL,
    "account_id" bigint NOT NULL,
    "response" attendance,
    "is_organizer" boolean NOT NULL DEFAULT FALSE
);

ALTER TABLE "public"."attendee" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."event" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "account_id" bigint NOT NULL,
    "cal_id" text NOT NULL,
    "series" text,
    "start_at" timestamp with time zone NOT NULL,
    "end_at" timestamp with time zone,
    "length" smallint,
    "title" text,
    "is_meeting" boolean NOT NULL DEFAULT FALSE,
    "is_online" boolean NOT NULL DEFAULT FALSE,
    "is_onsite" boolean NOT NULL DEFAULT FALSE,
    "is_offsite" boolean NOT NULL DEFAULT FALSE,
    "raw" jsonb
);

COMMENT ON COLUMN public.event.cal_id IS 'Unique and consistent ID within an individual account';

COMMENT ON COLUMN public.event.series IS 'ID shared between members of a recurring series';

ALTER TABLE "public"."event" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."domain" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "domain" text NOT NULL,
    "organization_id" bigint
);

ALTER TABLE "public"."domain" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."organization" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "name" text
);

ALTER TABLE "public"."organization" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."account" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "email" text NOT NULL,
    "name" text,
    "organization_id" bigint,
    "user_id" uuid REFERENCES auth.users ON DELETE SET NULL,
    "provider" provider,
    "credentials" jsonb
);

ALTER TABLE "public"."account" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX event_pkey ON public.event USING btree (id);

CREATE INDEX event_account_id_key ON public.event USING btree (account_id);

CREATE UNIQUE INDEX event_account_id_cal_id_key ON public.event USING btree (account_id, cal_id);

CREATE UNIQUE INDEX attendee_pkey ON public.attendee USING btree (event_id, account_id);

CREATE UNIQUE INDEX organization_pkey ON public.organization USING btree (id);

CREATE UNIQUE INDEX account_pkey ON public.account USING btree (id);

CREATE UNIQUE INDEX account_email_key ON public.account USING btree (email);

CREATE UNIQUE INDEX domain_key ON public.domain USING btree (DOMAIN);

ALTER TABLE "public"."event"
    ADD CONSTRAINT "event_pkey" PRIMARY KEY USING INDEX "event_pkey";

ALTER TABLE "public"."event"
    ADD CONSTRAINT "event_account_id_fkey" FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."event" validate CONSTRAINT "event_account_id_fkey";

ALTER TABLE "public"."organization"
    ADD CONSTRAINT "organization_pkey" PRIMARY KEY USING INDEX "organization_pkey";

ALTER TABLE "public"."attendee"
    ADD CONSTRAINT "attendee_event_id_fkey" FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."attendee" validate CONSTRAINT "attendee_event_id_fkey";

ALTER TABLE "public"."attendee"
    ADD CONSTRAINT "attendee_account_id_fkey" FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."attendee" validate CONSTRAINT "attendee_account_id_fkey";

ALTER TABLE "public"."account"
    ADD CONSTRAINT "account_pkey" PRIMARY KEY USING INDEX "account_pkey";

ALTER TABLE "public"."account"
    ADD CONSTRAINT "account_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE SET NULL NOT valid;

ALTER TABLE "public"."account" validate CONSTRAINT "account_organization_id_fkey";

ALTER TABLE "public"."account" validate CONSTRAINT "account_user_id_fkey";

SET check_function_bodies = OFF;

