name = "sync"
main = "src/index.ts"
compatibility_date = "2023-05-12"
node_compat = true
logpush = true

# Worker defines a binding, named "QUEUE", which gives it a capability
# to send messages to a Queue, named "my-queue".
[[queues.producers]]
  queue = "sync-queue"
  binding = "QUEUE"

# Worker also receives messages from the Queue, named "my-queue".
[[queues.consumers]]
  queue = "sync-queue"
  max_batch_size = 1    # Max messages per batch
  max_batch_timeout = 1 # Max seconds to wait before batch is full
  max_retries = 3       # Max retries per batch

[env.production]
  vars = { ENV = "production" }

[env.development]
  vars = { ENV = "development" }
#
# [placement]
#   mode = "smart"
